on:
  push:
    branches:
      - main
      - totem-prospector  # Ensure the branch you are working on is listed here
  pull_request:
    branches:
      - main
      - totem-prospector  # Ensure the branch you are working on is listed here
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

